#!/usr/bin/bash
#PBS -l walltime=12:00:00
#PBS -l mem=1Gb
#PBS -l ncpus=12
#PBS -l ngpus=1
#PBS -j oe
set -e

lscpu

cd "${PBS_O_WORKDIR}"

/srv/scratch/${USER}/.namd_cuda/namd3 "+p$(nproc)" prod.namd > prod.log
