#!/usr/bin/bash
#PBS -l walltime=12:00:00
#PBS -l mem=1Gb
#PBS -l ncpus=1
#PBS -j oe
set -e

lscpu

cd "${PBS_O_WORKDIR}"

module add crest

crest mobley_7532833.xyz --chrg 0 --uhf 0 -T 1 --noreftopo > crest.log
