#!/usr/bin/bash
#PBS -l walltime=12:00:00
#PBS -l mem=1Gb
#PBS -l ncpus=1
#PBS -j oe
set -e

lscpu

cd "${PBS_O_WORKDIR}"

module add crest

crest mobley_1261349.xyz --chrg 0 --uhf 0 -T 16 --noreftopo > crest.log
